# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WetherApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WetherApp
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'Firebase', '~> 4.0'
  pod 'FirebaseDatabase', '~> 4.0'
  pod 'NVActivityIndicatorView', '~> 3.7'
  pod 'SCLAlertView', '~> 0.7'

  target 'WetherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WetherAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
